# Use root/example as user/password credentials
version: '3.5'

services:

  mongo:
    image: mongo
    container_name: monge-server
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo-volume:/data/db